// Generated by tools/event_source_registry.py. Do not edit.
package cool.jacoblin.particeps.core.definition

import com.google.gson.JsonElement
import com.google.gson.JsonObject
import java.math.BigInteger

enum class GeneratedProfileFieldType { BOOLEAN, ENUM, ENUM_ARRAY, INTEGER, OBJECT, STRING }
enum class GeneratedLengthUnit { UTF16_CODE_UNITS, UTF8_BYTES }

data class GeneratedProfileFieldContract(
    val type: GeneratedProfileFieldType,
    val required: Boolean,
    val unit: String,
    val meaning: String,
    val authoringDefault: JsonElement,
    val minimum: BigInteger? = null,
    val maximum: BigInteger? = null,
    val minimumLength: Int? = null,
    val maximumLength: Int? = null,
    val lengthUnit: GeneratedLengthUnit? = null,
    val enumValues: List<String> = emptyList(),
    val minimumItems: Int? = null,
    val maximumItems: Int? = null,
    val lessThanOrEqualField: String? = null,
    val fields: Map<String, GeneratedProfileFieldContract> = emptyMap(),
) {
    fun accepts(value: JsonElement): Boolean = when (type) {
        GeneratedProfileFieldType.BOOLEAN -> value.isJsonPrimitive && value.asJsonPrimitive.isBoolean
        GeneratedProfileFieldType.INTEGER -> value.isJsonPrimitive && value.asJsonPrimitive.isNumber && canonicalInteger(value.asString)?.let { (minimum == null || it >= minimum) && (maximum == null || it <= maximum) } == true
        GeneratedProfileFieldType.STRING -> value.isJsonPrimitive && value.asJsonPrimitive.isString && stringLength(value.asString).let { (minimumLength == null || it >= minimumLength) && (maximumLength == null || it <= maximumLength) }
        GeneratedProfileFieldType.ENUM -> value.isJsonPrimitive && value.asJsonPrimitive.isString && value.asString in enumValues
        GeneratedProfileFieldType.ENUM_ARRAY -> value.isJsonArray && value.asJsonArray.mapNotNull { item -> item.takeIf(JsonElement::isJsonPrimitive)?.asJsonPrimitive?.takeIf { it.isString }?.asString }.let { items -> items.size == value.asJsonArray.size() && items == items.sorted().distinct() && items.all(enumValues::contains) && (minimumItems == null || items.size >= minimumItems) && (maximumItems == null || items.size <= maximumItems) }
        GeneratedProfileFieldType.OBJECT -> value.isJsonObject && acceptsObject(value.asJsonObject)
    }

    fun acceptsObject(value: JsonObject): Boolean =
        value.keySet().all(fields::containsKey) &&
            fields.all { (name, contract) -> (!contract.required && !value.has(name)) || (value.has(name) && contract.accepts(value.get(name))) } &&
            fields.all { (name, contract) -> contract.lessThanOrEqualField?.let { upper -> !value.has(name) || !value.has(upper) || value.get(name).asBigInteger() <= value.get(upper).asBigInteger() } ?: true }

    private fun stringLength(value: String): Int = if (lengthUnit == GeneratedLengthUnit.UTF8_BYTES) value.toByteArray(Charsets.UTF_8).size else value.length
    private fun JsonElement.asBigInteger(): BigInteger = canonicalInteger(asString) ?: error("validated integer expected")
    private companion object {
        val INTEGER = Regex("0|-?[1-9][0-9]*")
        fun canonicalInteger(value: String): BigInteger? = value.takeIf(INTEGER::matches)?.toBigIntegerOrNull()
    }
}

data class GeneratedCollectorProfileContract(
    val sourceId: String,
    val fields: Map<String, GeneratedProfileFieldContract>,
) {
    fun accepts(config: JsonObject): Boolean = GeneratedProfileFieldContract(
        type = GeneratedProfileFieldType.OBJECT,
        required = true,
        unit = "none",
        meaning = "collector profile",
        authoringDefault = JsonObject(),
        fields = fields,
    ).acceptsObject(config)
}

sealed interface CollectorProfileConfiguration {
    val sourceId: String
}

enum class LocationV1PriorityValue(val wireValue: String) {
    BALANCED("BALANCED"),
    HIGH_ACCURACY("HIGH_ACCURACY"),
    ;

    companion object {
        fun fromWire(value: String): LocationV1PriorityValue = entries.singleOrNull { it.wireValue == value }
            ?: throw IllegalArgumentException("Unknown location.v1.priority value: $value")
    }
}

enum class NetworkUsageV1TransportsValue(val wireValue: String) {
    MOBILE("mobile"),
    WIFI("wifi"),
    ;

    companion object {
        fun fromWire(value: String): NetworkUsageV1TransportsValue = entries.singleOrNull { it.wireValue == value }
            ?: throw IllegalArgumentException("Unknown network_usage.v1.transports value: $value")
    }
}

data class AccelerometerV1ProfileConfiguration(
    val maximumReportLatencyUs: Long,
    val samplingPeriodUs: Long,
    override val sourceId: String = SOURCE_ID,
) : CollectorProfileConfiguration {
    init {
        require(sourceId == SOURCE_ID) { "Collector profile source ID is immutable" }
        require(maximumReportLatencyUs in 0L..60000000L) { "Invalid accelerometer.v1.maximum_report_latency_us" }
        require(samplingPeriodUs in 5000L..1000000L) { "Invalid accelerometer.v1.sampling_period_us" }
    }

    companion object { const val SOURCE_ID: String = "accelerometer.v1" }
}

data class AmbientLightV1ProfileConfiguration(
    val changeThresholdMillilux: Long,
    val samplingPeriodUs: Long,
    override val sourceId: String = SOURCE_ID,
) : CollectorProfileConfiguration {
    init {
        require(sourceId == SOURCE_ID) { "Collector profile source ID is immutable" }
        require(changeThresholdMillilux in 0L..100000000L) { "Invalid ambient_light.v1.change_threshold_millilux" }
        require(samplingPeriodUs in 200000L..10000000L) { "Invalid ambient_light.v1.sampling_period_us" }
    }

    companion object { const val SOURCE_ID: String = "ambient_light.v1" }
}

data class AppLifecycleV1ProfileConfiguration(
    override val sourceId: String = SOURCE_ID,
) : CollectorProfileConfiguration {
    init {
        require(sourceId == SOURCE_ID) { "Collector profile source ID is immutable" }
    }

    companion object { const val SOURCE_ID: String = "app_lifecycle.v1" }
}

data class BatteryStateV1ProfileConfiguration(
    override val sourceId: String = SOURCE_ID,
) : CollectorProfileConfiguration {
    init {
        require(sourceId == SOURCE_ID) { "Collector profile source ID is immutable" }
    }

    companion object { const val SOURCE_ID: String = "battery_state.v1" }
}

data class GyroscopeV1ProfileConfiguration(
    val maximumReportLatencyUs: Long,
    val samplingPeriodUs: Long,
    override val sourceId: String = SOURCE_ID,
) : CollectorProfileConfiguration {
    init {
        require(sourceId == SOURCE_ID) { "Collector profile source ID is immutable" }
        require(maximumReportLatencyUs in 0L..60000000L) { "Invalid gyroscope.v1.maximum_report_latency_us" }
        require(samplingPeriodUs in 5000L..1000000L) { "Invalid gyroscope.v1.sampling_period_us" }
    }

    companion object { const val SOURCE_ID: String = "gyroscope.v1" }
}

data class KeyboardTouchV1ProfileConfiguration(
    val trajectorySamplingHz: Long,
    override val sourceId: String = SOURCE_ID,
) : CollectorProfileConfiguration {
    init {
        require(sourceId == SOURCE_ID) { "Collector profile source ID is immutable" }
        require(trajectorySamplingHz in 1L..120L) { "Invalid keyboard_touch.v1.trajectory_sampling_hz" }
    }

    companion object { const val SOURCE_ID: String = "keyboard_touch.v1" }
}

data class LocationV1ProfileConfiguration(
    val intervalMillis: Long,
    val maximumBatchDelayMillis: Long,
    val minimumDisplacementMillimeters: Long,
    val minimumIntervalMillis: Long,
    val priority: LocationV1PriorityValue,
    override val sourceId: String = SOURCE_ID,
) : CollectorProfileConfiguration {
    init {
        require(sourceId == SOURCE_ID) { "Collector profile source ID is immutable" }
        require(intervalMillis in 1000L..3600000L) { "Invalid location.v1.interval_millis" }
        require(maximumBatchDelayMillis in 0L..86400000L) { "Invalid location.v1.maximum_batch_delay_millis" }
        require(minimumDisplacementMillimeters in 0L..10000000L) { "Invalid location.v1.minimum_displacement_millimeters" }
        require(minimumIntervalMillis in 500L..3600000L) { "Invalid location.v1.minimum_interval_millis" }
        require(minimumIntervalMillis <= intervalMillis) { "location.v1.minimum_interval_millis exceeds interval_millis" }
    }

    companion object { const val SOURCE_ID: String = "location.v1" }
}

data class NetworkStateV1ProfileConfiguration(
    val includeBandwidthEstimates: Boolean,
    override val sourceId: String = SOURCE_ID,
) : CollectorProfileConfiguration {
    init {
        require(sourceId == SOURCE_ID) { "Collector profile source ID is immutable" }
    }

    companion object { const val SOURCE_ID: String = "network_state.v1" }
}

data class NetworkUsageV1ProfileConfiguration(
    val pollIntervalSeconds: Long,
    val transports: List<NetworkUsageV1TransportsValue>,
    override val sourceId: String = SOURCE_ID,
) : CollectorProfileConfiguration {
    init {
        require(sourceId == SOURCE_ID) { "Collector profile source ID is immutable" }
        require(pollIntervalSeconds in 15L..86400L) { "Invalid network_usage.v1.poll_interval_seconds" }
        require(transports.size in 1..2 && transports.map { it.wireValue } == transports.map { it.wireValue }.sorted().distinct()) { "Invalid network_usage.v1.transports" }
    }

    companion object { const val SOURCE_ID: String = "network_usage.v1" }
}

data class ProximityV1ProfileConfiguration(
    val changeThresholdMillimeters: Long,
    val minimumEventIntervalMs: Long,
    override val sourceId: String = SOURCE_ID,
) : CollectorProfileConfiguration {
    init {
        require(sourceId == SOURCE_ID) { "Collector profile source ID is immutable" }
        require(changeThresholdMillimeters in 0L..10000L) { "Invalid proximity.v1.change_threshold_millimeters" }
        require(minimumEventIntervalMs in 100L..60000L) { "Invalid proximity.v1.minimum_event_interval_ms" }
    }

    companion object { const val SOURCE_ID: String = "proximity.v1" }
}

data class TemporalContextV1ProfileConfiguration(
    override val sourceId: String = SOURCE_ID,
) : CollectorProfileConfiguration {
    init {
        require(sourceId == SOURCE_ID) { "Collector profile source ID is immutable" }
    }

    companion object { const val SOURCE_ID: String = "temporal_context.v1" }
}

data class UsageEventsV1ProfileConfiguration(
    val pollIntervalSeconds: Long,
    override val sourceId: String = SOURCE_ID,
) : CollectorProfileConfiguration {
    init {
        require(sourceId == SOURCE_ID) { "Collector profile source ID is immutable" }
        require(pollIntervalSeconds in 15L..86400L) { "Invalid usage_events.v1.poll_interval_seconds" }
    }

    companion object { const val SOURCE_ID: String = "usage_events.v1" }
}

object GeneratedCollectorProfileCodec {
    fun decode(sourceId: String, config: JsonObject): CollectorProfileConfiguration {
        GeneratedCollectorProfileContracts.requireValid(sourceId, config)
        return when (sourceId) {
            "accelerometer.v1" -> AccelerometerV1ProfileConfiguration(
                maximumReportLatencyUs = config.get("maximum_report_latency_us").asLong,
                samplingPeriodUs = config.get("sampling_period_us").asLong,
            )
            "ambient_light.v1" -> AmbientLightV1ProfileConfiguration(
                changeThresholdMillilux = config.get("change_threshold_millilux").asLong,
                samplingPeriodUs = config.get("sampling_period_us").asLong,
            )
            "app_lifecycle.v1" -> AppLifecycleV1ProfileConfiguration(
            )
            "battery_state.v1" -> BatteryStateV1ProfileConfiguration(
            )
            "gyroscope.v1" -> GyroscopeV1ProfileConfiguration(
                maximumReportLatencyUs = config.get("maximum_report_latency_us").asLong,
                samplingPeriodUs = config.get("sampling_period_us").asLong,
            )
            "keyboard_touch.v1" -> KeyboardTouchV1ProfileConfiguration(
                trajectorySamplingHz = config.get("trajectory_sampling_hz").asLong,
            )
            "location.v1" -> LocationV1ProfileConfiguration(
                intervalMillis = config.get("interval_millis").asLong,
                maximumBatchDelayMillis = config.get("maximum_batch_delay_millis").asLong,
                minimumDisplacementMillimeters = config.get("minimum_displacement_millimeters").asLong,
                minimumIntervalMillis = config.get("minimum_interval_millis").asLong,
                priority = LocationV1PriorityValue.fromWire(config.get("priority").asString),
            )
            "network_state.v1" -> NetworkStateV1ProfileConfiguration(
                includeBandwidthEstimates = config.get("include_bandwidth_estimates").asBoolean,
            )
            "network_usage.v1" -> NetworkUsageV1ProfileConfiguration(
                pollIntervalSeconds = config.get("poll_interval_seconds").asLong,
                transports = config.get("transports").asJsonArray.map { NetworkUsageV1TransportsValue.fromWire(it.asString) },
            )
            "proximity.v1" -> ProximityV1ProfileConfiguration(
                changeThresholdMillimeters = config.get("change_threshold_millimeters").asLong,
                minimumEventIntervalMs = config.get("minimum_event_interval_ms").asLong,
            )
            "temporal_context.v1" -> TemporalContextV1ProfileConfiguration(
            )
            "usage_events.v1" -> UsageEventsV1ProfileConfiguration(
                pollIntervalSeconds = config.get("poll_interval_seconds").asLong,
            )
            else -> throw IllegalArgumentException("Unknown collector source: $sourceId")
        }
    }

    fun encode(profile: CollectorProfileConfiguration): JsonObject = JsonObject().apply {
        when (profile) {
            is AccelerometerV1ProfileConfiguration -> {
                add("maximum_report_latency_us", com.google.gson.JsonPrimitive(profile.maximumReportLatencyUs))
                add("sampling_period_us", com.google.gson.JsonPrimitive(profile.samplingPeriodUs))
            }
            is AmbientLightV1ProfileConfiguration -> {
                add("change_threshold_millilux", com.google.gson.JsonPrimitive(profile.changeThresholdMillilux))
                add("sampling_period_us", com.google.gson.JsonPrimitive(profile.samplingPeriodUs))
            }
            is AppLifecycleV1ProfileConfiguration -> {
            }
            is BatteryStateV1ProfileConfiguration -> {
            }
            is GyroscopeV1ProfileConfiguration -> {
                add("maximum_report_latency_us", com.google.gson.JsonPrimitive(profile.maximumReportLatencyUs))
                add("sampling_period_us", com.google.gson.JsonPrimitive(profile.samplingPeriodUs))
            }
            is KeyboardTouchV1ProfileConfiguration -> {
                add("trajectory_sampling_hz", com.google.gson.JsonPrimitive(profile.trajectorySamplingHz))
            }
            is LocationV1ProfileConfiguration -> {
                add("interval_millis", com.google.gson.JsonPrimitive(profile.intervalMillis))
                add("maximum_batch_delay_millis", com.google.gson.JsonPrimitive(profile.maximumBatchDelayMillis))
                add("minimum_displacement_millimeters", com.google.gson.JsonPrimitive(profile.minimumDisplacementMillimeters))
                add("minimum_interval_millis", com.google.gson.JsonPrimitive(profile.minimumIntervalMillis))
                add("priority", com.google.gson.JsonPrimitive(profile.priority.wireValue))
            }
            is NetworkStateV1ProfileConfiguration -> {
                add("include_bandwidth_estimates", com.google.gson.JsonPrimitive(profile.includeBandwidthEstimates))
            }
            is NetworkUsageV1ProfileConfiguration -> {
                add("poll_interval_seconds", com.google.gson.JsonPrimitive(profile.pollIntervalSeconds))
                add("transports", com.google.gson.JsonArray().apply { profile.transports.forEach { add(it.wireValue) } })
            }
            is ProximityV1ProfileConfiguration -> {
                add("change_threshold_millimeters", com.google.gson.JsonPrimitive(profile.changeThresholdMillimeters))
                add("minimum_event_interval_ms", com.google.gson.JsonPrimitive(profile.minimumEventIntervalMs))
            }
            is TemporalContextV1ProfileConfiguration -> {
            }
            is UsageEventsV1ProfileConfiguration -> {
                add("poll_interval_seconds", com.google.gson.JsonPrimitive(profile.pollIntervalSeconds))
            }
        }
    }

    fun authoringDefault(sourceId: String): CollectorProfileConfiguration {
        val contract = requireNotNull(GeneratedCollectorProfileContracts[sourceId]) { "Unknown collector source: $sourceId" }
        val config = JsonObject().apply { contract.fields.forEach { (name, field) -> add(name, field.authoringDefault.deepCopy()) } }
        return decode(sourceId, config)
    }
}

object GeneratedCollectorProfileContracts {
    const val REGISTRY_SHA256: String = "53e3814c0f159a579d303f51bff94293188d4afd4f8fb82d19616c782483299c"
    val contracts: Map<String, GeneratedCollectorProfileContract> = listOf(
        GeneratedCollectorProfileContract(
            sourceId = "accelerometer.v1",
            fields = mapOf(
                "maximum_report_latency_us" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "microsecond",
                    meaning = "Maximum Android hardware FIFO batching latency.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("1000000")),
                    minimum = BigInteger("0"),
                    maximum = BigInteger("60000000"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
                "sampling_period_us" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "microsecond",
                    meaning = "Requested Android sensor sampling period; this is a hint, not an achieved-rate guarantee.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("100000")),
                    minimum = BigInteger("5000"),
                    maximum = BigInteger("1000000"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
            ),
        ),
        GeneratedCollectorProfileContract(
            sourceId = "ambient_light.v1",
            fields = mapOf(
                "change_threshold_millilux" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "millilux",
                    meaning = "Minimum illuminance change from the last emitted sample. The newest changed on-change sample inside the rate interval is retained and emitted later with its original observation and hardware times.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("1000")),
                    minimum = BigInteger("0"),
                    maximum = BigInteger("100000000"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
                "sampling_period_us" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "microsecond",
                    meaning = "Minimum emitted-sample period and Android sensor request period; rate limiting coalesces to the newest meaningful sample rather than dropping it.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("1000000")),
                    minimum = BigInteger("200000"),
                    maximum = BigInteger("10000000"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
            ),
        ),
        GeneratedCollectorProfileContract(
            sourceId = "app_lifecycle.v1",
            fields = mapOf(
            ),
        ),
        GeneratedCollectorProfileContract(
            sourceId = "battery_state.v1",
            fields = mapOf(
            ),
        ),
        GeneratedCollectorProfileContract(
            sourceId = "gyroscope.v1",
            fields = mapOf(
                "maximum_report_latency_us" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "microsecond",
                    meaning = "Maximum Android hardware FIFO batching latency.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("1000000")),
                    minimum = BigInteger("0"),
                    maximum = BigInteger("60000000"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
                "sampling_period_us" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "microsecond",
                    meaning = "Requested Android sensor sampling period; this is a hint, not an achieved-rate guarantee.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("100000")),
                    minimum = BigInteger("5000"),
                    maximum = BigInteger("1000000"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
            ),
        ),
        GeneratedCollectorProfileContract(
            sourceId = "keyboard_touch.v1",
            fields = mapOf(
                "trajectory_sampling_hz" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "hertz",
                    meaning = "Maximum MOVE-event sampling rate; boundary actions are not rate limited.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("60")),
                    minimum = BigInteger("1"),
                    maximum = BigInteger("120"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
            ),
        ),
        GeneratedCollectorProfileContract(
            sourceId = "location.v1",
            fields = mapOf(
                "interval_millis" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "millisecond",
                    meaning = "Requested fused-location interval.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("60000")),
                    minimum = BigInteger("1000"),
                    maximum = BigInteger("3600000"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
                "maximum_batch_delay_millis" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "millisecond",
                    meaning = "Maximum fused-location batching delay.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("300000")),
                    minimum = BigInteger("0"),
                    maximum = BigInteger("86400000"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
                "minimum_displacement_millimeters" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "millimeter",
                    meaning = "Requested minimum displacement, represented without a floating-point configuration value.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("0")),
                    minimum = BigInteger("0"),
                    maximum = BigInteger("10000000"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
                "minimum_interval_millis" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "millisecond",
                    meaning = "Fastest requested fused-location interval; additionally bounded by interval_millis.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("30000")),
                    minimum = BigInteger("500"),
                    maximum = BigInteger("3600000"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = "interval_millis",
                ),
                "priority" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.ENUM,
                    required = true,
                    unit = "none",
                    meaning = "Fused-location power/accuracy priority within precise location.",
                    authoringDefault = com.google.gson.JsonPrimitive("BALANCED"),
                    minimum = null,
                    maximum = null,
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = listOf("BALANCED", "HIGH_ACCURACY"),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
            ),
        ),
        GeneratedCollectorProfileContract(
            sourceId = "network_state.v1",
            fields = mapOf(
                "include_bandwidth_estimates" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.BOOLEAN,
                    required = true,
                    unit = "none",
                    meaning = "Whether capability events include Android link-bandwidth estimates.",
                    authoringDefault = com.google.gson.JsonPrimitive(false),
                    minimum = null,
                    maximum = null,
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
            ),
        ),
        GeneratedCollectorProfileContract(
            sourceId = "network_usage.v1",
            fields = mapOf(
                "poll_interval_seconds" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "second",
                    meaning = "Interval between device-total counter queries.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("900")),
                    minimum = BigInteger("15"),
                    maximum = BigInteger("86400"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
                "transports" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.ENUM_ARRAY,
                    required = true,
                    unit = "none",
                    meaning = "Device-total transports to query.",
                    authoringDefault = com.google.gson.JsonArray().apply { add(com.google.gson.JsonPrimitive("mobile")); add(com.google.gson.JsonPrimitive("wifi")) },
                    minimum = null,
                    maximum = null,
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = listOf("mobile", "wifi"),
                    minimumItems = 1,
                    maximumItems = 2,
                    lessThanOrEqualField = null,
                ),
            ),
        ),
        GeneratedCollectorProfileContract(
            sourceId = "proximity.v1",
            fields = mapOf(
                "change_threshold_millimeters" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "millimeter",
                    meaning = "Minimum raw-distance change before another same-state event is emitted.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("0")),
                    minimum = BigInteger("0"),
                    maximum = BigInteger("10000"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
                "minimum_event_interval_ms" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "millisecond",
                    meaning = "Minimum interval between emitted events; the latest pending state is retained.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("1000")),
                    minimum = BigInteger("100"),
                    maximum = BigInteger("60000"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
            ),
        ),
        GeneratedCollectorProfileContract(
            sourceId = "temporal_context.v1",
            fields = mapOf(
            ),
        ),
        GeneratedCollectorProfileContract(
            sourceId = "usage_events.v1",
            fields = mapOf(
                "poll_interval_seconds" to
                GeneratedProfileFieldContract(
                    type = GeneratedProfileFieldType.INTEGER,
                    required = true,
                    unit = "second",
                    meaning = "Interval between UsageStats queries; 15 seconds is required when this source drives automation.",
                    authoringDefault = com.google.gson.JsonPrimitive(BigInteger("900")),
                    minimum = BigInteger("15"),
                    maximum = BigInteger("86400"),
                    minimumLength = null,
                    maximumLength = null,
                    lengthUnit = null,
                    enumValues = emptyList(),
                    minimumItems = null,
                    maximumItems = null,
                    lessThanOrEqualField = null,
                ),
            ),
        ),
    ).associateBy(GeneratedCollectorProfileContract::sourceId)

    operator fun get(sourceId: String): GeneratedCollectorProfileContract? = contracts[sourceId]
    fun requireValid(sourceId: String, config: JsonObject) {
        requireNotNull(contracts[sourceId]) { "Unknown collector source: $sourceId" }
            .also { require(it.accepts(config)) { "Invalid profile config for $sourceId" } }
    }
}
