#!/usr/bin/env python3
"""Validate and canonicalize the closed-world ADC collector catalog."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CATALOG = ROOT / "protocol/v1/collector-catalog.json"
DEFAULT_KOTLIN_CONTRACT = (
    ROOT
    / "core/collector-api/src/main/kotlin/cool/linc/androiddatacollector/core/collector/ProtocolEventContracts.kt"
)
ID = re.compile(r"[a-z][a-z0-9_.-]{2,63}\Z")
FIELD = re.compile(r"[a-z][a-z0-9_]{1,63}\Z")
EVENT_TYPE = re.compile(r"[A-Z][A-Z0-9_]{1,63}\Z")
MODULE = re.compile(r":[a-z][a-z0-9-]*(?::[a-z][a-z0-9-]*)*\Z")


class CatalogError(ValueError):
    """The catalog is not the one unambiguous language-neutral schema."""


def _reject_duplicate(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise CatalogError(f"duplicate JSON member: {key}")
        result[key] = value
    return result


def _reject_float(value: str) -> None:
    raise CatalogError(f"JSON non-integral number is forbidden: {value}")


def load(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(
            path.read_text(encoding="utf-8"),
            object_pairs_hook=_reject_duplicate,
            parse_float=_reject_float,
            parse_constant=_reject_float,
        )
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise CatalogError(str(error)) from error
    if not isinstance(value, dict):
        raise CatalogError("catalog root must be an object")
    return value


def canonical_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")


def _kotlin_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _kotlin_double(value: int) -> str:
    return f"{value}.0"


def render_kotlin_contract(catalog: dict[str, Any]) -> str:
    """Generate the sole Kotlin runtime projection of implemented event contracts."""
    collectors = [
        collector
        for collector in catalog["collectors"]
        if collector["implementation"]["status"] == "implemented"
        and "android" in collector["platforms"]
    ]
    lines = [
        "// Generated by tools/catalog.py from protocol/v1/collector-catalog.json. Do not edit.",
        "package cool.linc.androiddatacollector.core.collector",
        "",
        "object ProtocolEventContracts {",
        "    val contracts: Map<String, CollectorEventContract> = mapOf(",
    ]
    for collector in collectors:
        lines.extend(
            [
                f'        {_kotlin_string(collector["id"])} to CollectorEventContract(',
                f'            payloadSchemaVersion = {collector["payload_schema_version"]},',
                f'            maximumEncodedEventBytes = {collector["maximum_encoded_event_bytes"]:,},'.replace(",", "_", 1),
                "            payloads = payloads(",
            ]
        )
        for payload in collector["payloads"]:
            types = ", ".join(_kotlin_string(value) for value in payload["types"])
            lines.extend(
                [
                    f"                listOf({types}) to EventPayloadContract(",
                    "                    fields = mapOf(",
                ]
            )
            for name, field in payload["fields"].items():
                arguments = [
                    f'type = EventFieldType.{field["type"].upper()}',
                    f'required = {str(field["required"]).lower()}',
                ]
                if "enum" in field:
                    values = ", ".join(_kotlin_string(value) for value in field["enum"])
                    arguments.append(f"enumValues = setOf({values})")
                if "minimum" in field:
                    arguments.append(f'minimum = {_kotlin_double(field["minimum"])}')
                if "maximum" in field:
                    arguments.append(f'maximum = {_kotlin_double(field["maximum"])}')
                if "maximum_length" in field:
                    arguments.append(f'maximumLength = {field["maximum_length"]}')
                lines.extend(
                    [
                        f'                        {_kotlin_string(name)} to EventFieldContract(',
                        *(f"                            {argument}," for argument in arguments),
                        "                        ),",
                    ]
                )
            lines.extend(
                [
                    "                    ),",
                    "                ),",
                ]
            )
        lines.extend(
            [
                "            ),",
                "        ),",
            ]
        )
    lines.extend(
        [
            "    )",
            "",
            "    operator fun get(collectorId: String): CollectorEventContract? = contracts[collectorId]",
            "",
            "    private fun payloads(",
            "        vararg groups: Pair<List<String>, EventPayloadContract>,",
            "    ): Map<String, EventPayloadContract> = buildMap {",
            "        groups.forEach { (types, contract) ->",
            "            types.forEach { type -> check(put(type, contract) == null) { \"Duplicate payload type\" } }",
            "        }",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def check_kotlin_contract(catalog: dict[str, Any], path: Path = DEFAULT_KOTLIN_CONTRACT) -> None:
    expected = render_kotlin_contract(catalog)
    try:
        actual = path.read_text(encoding="utf-8")
    except OSError as error:
        raise CatalogError(f"generated Kotlin contract is absent: {path}") from error
    if actual != expected:
        raise CatalogError(
            "generated Kotlin contract is stale; run "
            "python3 tools/catalog.py generate-kotlin"
        )


def _object(value: Any, path: str, exact: Iterable[str]) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise CatalogError(f"{path} must be an object")
    expected = set(exact)
    actual = set(value)
    if actual != expected:
        raise CatalogError(
            f"{path} members differ: missing={sorted(expected-actual)}, "
            f"unknown={sorted(actual-expected)}"
        )
    return value


def _list(value: Any, path: str) -> list[Any]:
    if not isinstance(value, list):
        raise CatalogError(f"{path} must be an array")
    return value


def _sorted_unique(values: list[Any], path: str) -> None:
    if values != sorted(values) or len(values) != len(set(values)):
        raise CatalogError(f"{path} must be sorted and unique")


def _string(value: Any, path: str, pattern: re.Pattern[str] | None = None) -> str:
    if not isinstance(value, str) or not value:
        raise CatalogError(f"{path} must be a non-empty string")
    if pattern and not pattern.fullmatch(value):
        raise CatalogError(f"{path} has invalid syntax: {value!r}")
    return value


def _integer(value: Any, path: str, minimum: int | None = None) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise CatalogError(f"{path} must be an integer")
    if minimum is not None and value < minimum:
        raise CatalogError(f"{path} must be at least {minimum}")
    return value


def _enum(values: Any, path: str) -> list[str]:
    result = _list(values, path)
    if not result or any(not isinstance(item, str) or not item for item in result):
        raise CatalogError(f"{path} must contain non-empty strings")
    _sorted_unique(result, path)
    return result


def _validate_config_field(field: Any, path: str) -> None:
    if not isinstance(field, dict):
        raise CatalogError(f"{path} must be an object")
    kind = field.get("type")
    common = {"type", "meaning", "unit"}
    required = {
        "integer": common | {"minimum", "maximum"},
        "boolean": common,
        "enum": common | {"enum"},
        "enum_array": common | {"items_enum", "minimum_items", "maximum_items"},
    }.get(kind)
    if required is None:
        raise CatalogError(f"{path} has unknown type or wrong members")
    allowed = required | ({"maximum_field"} if kind == "integer" else set())
    if not required <= set(field) or not set(field) <= allowed:
        raise CatalogError(f"{path} has unknown type or wrong members")
    _string(field["meaning"], f"{path}.meaning")
    _string(field["unit"], f"{path}.unit")
    if kind == "integer":
        low = _integer(field["minimum"], f"{path}.minimum")
        high = _integer(field["maximum"], f"{path}.maximum")
        if low > high:
            raise CatalogError(f"{path} minimum exceeds maximum")
        if "maximum_field" in field:
            _string(field["maximum_field"], f"{path}.maximum_field", FIELD)
    elif kind == "enum":
        _enum(field["enum"], f"{path}.enum")
    elif kind == "enum_array":
        _enum(field["items_enum"], f"{path}.items_enum")
        low = _integer(field["minimum_items"], f"{path}.minimum_items", 0)
        high = _integer(field["maximum_items"], f"{path}.maximum_items", 0)
        if low > high:
            raise CatalogError(f"{path} minimum_items exceeds maximum_items")


def _validate_payload_field(field: Any, path: str) -> None:
    if not isinstance(field, dict):
        raise CatalogError(f"{path} must be an object")
    kind = field.get("type")
    common = {"type", "meaning", "unit", "clock_basis", "required"}
    optional = {
        "boolean": set(),
        "decimal_string": {"minimum", "maximum"},
        "enum": {"enum"},
        "float32": {"minimum", "maximum"},
        "float64": {"minimum", "maximum"},
        "int32": {"minimum", "maximum"},
        "json_string": {"maximum_length"},
        "string": {"maximum_length"},
    }.get(kind)
    required = common | ({"enum"} if kind == "enum" else set())
    if optional is None or not required <= set(field) or not set(field) <= common | optional:
        raise CatalogError(f"{path} has unknown type or wrong members")
    _string(field["meaning"], f"{path}.meaning")
    _string(field["unit"], f"{path}.unit")
    if field["clock_basis"] is not None:
        _string(field["clock_basis"], f"{path}.clock_basis")
    if not isinstance(field["required"], bool):
        raise CatalogError(f"{path}.required must be boolean")
    if kind == "enum":
        _enum(field["enum"], f"{path}.enum")
    for key in ("minimum", "maximum"):
        if key in field:
            _integer(field[key], f"{path}.{key}")
    if "maximum_length" in field:
        _integer(field["maximum_length"], f"{path}.maximum_length", 1)
    if "minimum" in field and "maximum" in field and field["minimum"] > field["maximum"]:
        raise CatalogError(f"{path} minimum exceeds maximum")
    if kind == "int32":
        for key in ("minimum", "maximum"):
            if key in field and not -(2**31) <= field[key] <= 2**31 - 1:
                raise CatalogError(f"{path}.{key} exceeds signed int32")


def _validate_module(module: str, status: str, root: Path | None, path: str) -> None:
    _string(module, path, MODULE)
    if root is None or status != "implemented":
        return
    parts = module.removeprefix(":").split(":")
    directory = root.joinpath(*parts)
    if not directory.is_dir():
        raise CatalogError(f"{path} claims missing implemented module {module}")


def validate(catalog: dict[str, Any], project_root: Path | None = None) -> None:
    root = _object(
        catalog,
        "$",
        {"catalog_format", "catalog_version", "collectors", "protocol_schema_version"},
    )
    if root["catalog_format"] != "adc-collector-catalog-v1":
        raise CatalogError("$.catalog_format must be adc-collector-catalog-v1")
    if root["catalog_version"] != 1 or root["protocol_schema_version"] != 1:
        raise CatalogError("catalog and protocol schema versions must be integer 1")
    collectors = _list(root["collectors"], "$.collectors")
    ids: list[str] = []
    for index, value in enumerate(collectors):
        path = f"$.collectors[{index}]"
        collector = _object(
            value,
            path,
            {
                "access",
                "configuration",
                "id",
                "implementation",
                "maximum_encoded_event_bytes",
                "payload_schema_version",
                "payloads",
                "platforms",
                "privacy_class",
                "rate_bound",
                "selectable",
            },
        )
        identifier = _string(collector["id"], f"{path}.id", ID)
        ids.append(identifier)
        if collector["privacy_class"] not in {"SENSITIVE", "RESTRICTED"}:
            raise CatalogError(f"{path}.privacy_class is unknown")
        if not isinstance(collector["selectable"], bool):
            raise CatalogError(f"{path}.selectable must be boolean")
        if collector["payload_schema_version"] != 1:
            raise CatalogError(f"{path}.payload_schema_version must be integer 1")
        size = _integer(
            collector["maximum_encoded_event_bytes"],
            f"{path}.maximum_encoded_event_bytes",
            128,
        )
        if size > 65_536:
            raise CatalogError(f"{path}.maximum_encoded_event_bytes exceeds 65536")
        platforms = _enum(collector["platforms"], f"{path}.platforms")
        if any(platform not in {"android", "ios"} for platform in platforms):
            raise CatalogError(f"{path}.platforms contains an unknown platform")

        implementation = _object(
            collector["implementation"],
            f"{path}.implementation",
            {"android_module", "status"},
        )
        if implementation["status"] not in {"implemented", "planned"}:
            raise CatalogError(f"{path}.implementation.status is unknown")
        _validate_module(
            implementation["android_module"],
            implementation["status"],
            project_root,
            f"{path}.implementation.android_module",
        )

        access = _list(collector["access"], f"{path}.access")
        access_keys: list[tuple[str, str]] = []
        for access_index, item in enumerate(access):
            access_path = f"{path}.access[{access_index}]"
            entry = _object(item, access_path, {"kind", "mode"})
            kind = _string(entry["kind"], f"{access_path}.kind", EVENT_TYPE)
            mode = entry["mode"]
            if mode not in {
                "hardware",
                "install_permission",
                "participant_setting",
                "runtime_permission",
                "special_access",
            }:
                raise CatalogError(f"{access_path}.mode is unknown")
            access_keys.append((kind, mode))
        _sorted_unique(access_keys, f"{path}.access")

        configuration = collector["configuration"]
        if configuration is None:
            if collector["selectable"]:
                raise CatalogError(f"{path}.configuration may be null only for runtime collectors")
        else:
            config = _object(configuration, f"{path}.configuration", {"fields", "required"})
            fields = config["fields"]
            if not isinstance(fields, dict):
                raise CatalogError(f"{path}.configuration.fields must be an object")
            if list(fields) != sorted(fields):
                raise CatalogError(f"{path}.configuration.fields must be sorted")
            required_value = _list(config["required"], f"{path}.configuration.required")
            required = (
                _enum(required_value, f"{path}.configuration.required")
                if required_value
                else []
            )
            if any(name not in fields for name in required):
                raise CatalogError(f"{path}.configuration.required names an unknown field")
            for name, field in fields.items():
                _string(name, f"{path}.configuration field name", FIELD)
                _validate_config_field(field, f"{path}.configuration.fields.{name}")
            for name, field in fields.items():
                maximum_field = field.get("maximum_field")
                if maximum_field is None:
                    continue
                referenced = fields.get(maximum_field)
                if maximum_field == name or referenced is None or referenced.get("type") != "integer":
                    raise CatalogError(
                        f"{path}.configuration.fields.{name}.maximum_field is not another integer field"
                    )

        rate = _object(
            collector["rate_bound"],
            f"{path}.rate_bound",
            {"enforced_by", "kind", "maximum_events_per_hour"},
        )
        _string(rate["enforced_by"], f"{path}.rate_bound.enforced_by")
        if rate["kind"] not in {
            "android_platform_cap",
            "collector_rate_limit",
            "not_enforced",
            "poll_configuration",
        }:
            raise CatalogError(f"{path}.rate_bound.kind is unknown")
        maximum = rate["maximum_events_per_hour"]
        if rate["kind"] == "not_enforced":
            if maximum is not None:
                raise CatalogError(f"{path}.rate_bound maximum must be null when not enforced")
        else:
            _integer(maximum, f"{path}.rate_bound.maximum_events_per_hour", 1)

        payloads = _list(collector["payloads"], f"{path}.payloads")
        if not payloads:
            raise CatalogError(f"{path}.payloads must not be empty")
        collector_types: set[str] = set()
        for payload_index, item in enumerate(payloads):
            payload_path = f"{path}.payloads[{payload_index}]"
            payload = _object(item, payload_path, {"fields", "types"})
            types = _enum(payload["types"], f"{payload_path}.types")
            for event_type in types:
                _string(event_type, f"{payload_path}.types", EVENT_TYPE)
                if event_type in collector_types:
                    raise CatalogError(f"payload type is repeated in {identifier}: {event_type}")
                collector_types.add(event_type)
            fields = payload["fields"]
            if not isinstance(fields, dict) or list(fields) != sorted(fields):
                raise CatalogError(f"{payload_path}.fields must be a sorted object")
            for name, field in fields.items():
                _string(name, f"{payload_path} field name", FIELD)
                _validate_payload_field(field, f"{payload_path}.fields.{name}")
    _sorted_unique(ids, "$.collectors[].id")


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("check", "canonical", "digest", "generate-kotlin"))
    parser.add_argument("path", nargs="?", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument(
        "--project-root",
        type=Path,
        default=ROOT,
        help="verify implemented Android module paths; use an empty value only through the API",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        catalog = load(args.path)
        validate(catalog, args.project_root.resolve())
    except CatalogError as error:
        print(f"catalog error: {error}", file=sys.stderr)
        return 1
    encoded = canonical_bytes(catalog)
    if args.command == "generate-kotlin":
        DEFAULT_KOTLIN_CONTRACT.parent.mkdir(parents=True, exist_ok=True)
        DEFAULT_KOTLIN_CONTRACT.write_text(render_kotlin_contract(catalog), encoding="utf-8")
        print(f"wrote {DEFAULT_KOTLIN_CONTRACT}")
    elif args.command == "canonical":
        sys.stdout.buffer.write(encoded + b"\n")
    elif args.command == "digest":
        print(hashlib.sha256(encoded).hexdigest())
    else:
        try:
            check_kotlin_contract(catalog)
        except CatalogError as error:
            print(f"catalog error: {error}", file=sys.stderr)
            return 1
        print(f"valid collector catalog: {len(catalog['collectors'])} collectors")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
