// Generated by tools/catalog.py from protocol/v1/collector-catalog.json. Do not edit.
package cool.linc.androiddatacollector.core.collector

object ProtocolEventContracts {
    val contracts: Map<String, CollectorEventContract> = mapOf(
        "accelerometer.v1" to CollectorEventContract(
            payloadSchemaVersion = 1,
            maximumEncodedEventBytes = 2_048,
            payloads = payloads(
                listOf("ACCELEROMETER_SAMPLE") to EventPayloadContract(
                    fields = mapOf(
                        "accuracy" to EventFieldContract(
                            type = EventFieldType.INT32,
                            required = true,
                        ),
                        "source_elapsed_realtime_nanos" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                        "x_meters_per_second_squared" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                        ),
                        "y_meters_per_second_squared" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                        ),
                        "z_meters_per_second_squared" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                        ),
                    ),
                ),
            ),
        ),
        "ambient_light.v1" to CollectorEventContract(
            payloadSchemaVersion = 1,
            maximumEncodedEventBytes = 1_024,
            payloads = payloads(
                listOf("AMBIENT_LIGHT_SAMPLE") to EventPayloadContract(
                    fields = mapOf(
                        "accuracy" to EventFieldContract(
                            type = EventFieldType.INT32,
                            required = true,
                        ),
                        "illuminance_lux" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                            minimum = 0.0,
                        ),
                        "source_elapsed_realtime_nanos" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                    ),
                ),
            ),
        ),
        "app_lifecycle.v1" to CollectorEventContract(
            payloadSchemaVersion = 1,
            maximumEncodedEventBytes = 2_048,
            payloads = payloads(
                listOf("ACTIVITY_CREATED", "ACTIVITY_DESTROYED", "ACTIVITY_INSTANCE_STATE_SAVED", "ACTIVITY_PAUSED", "ACTIVITY_RESUMED", "ACTIVITY_STARTED", "ACTIVITY_STOPPED") to EventPayloadContract(
                    fields = mapOf(
                        "activity_class" to EventFieldContract(
                            type = EventFieldType.STRING,
                            required = true,
                            maximumLength = 512,
                        ),
                    ),
                ),
            ),
        ),
        "battery_state.v1" to CollectorEventContract(
            payloadSchemaVersion = 1,
            maximumEncodedEventBytes = 1_024,
            payloads = payloads(
                listOf("BATTERY_STATE") to EventPayloadContract(
                    fields = mapOf(
                        "charging_source" to EventFieldContract(
                            type = EventFieldType.ENUM,
                            required = true,
                            enumValues = setOf("AC", "DOCK", "MULTIPLE", "NONE", "UNKNOWN", "USB", "WIRELESS"),
                        ),
                        "charging_state" to EventFieldContract(
                            type = EventFieldType.ENUM,
                            required = true,
                            enumValues = setOf("CHARGING", "DISCHARGING", "FULL", "NOT_CHARGING", "UNKNOWN"),
                        ),
                        "percentage" to EventFieldContract(
                            type = EventFieldType.INT32,
                            required = true,
                            minimum = 0.0,
                            maximum = 100.0,
                        ),
                        "power_save_enabled" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = true,
                        ),
                    ),
                ),
            ),
        ),
        "gyroscope.v1" to CollectorEventContract(
            payloadSchemaVersion = 1,
            maximumEncodedEventBytes = 2_048,
            payloads = payloads(
                listOf("GYROSCOPE_SAMPLE") to EventPayloadContract(
                    fields = mapOf(
                        "accuracy" to EventFieldContract(
                            type = EventFieldType.INT32,
                            required = true,
                        ),
                        "source_elapsed_realtime_nanos" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                        "x_radians_per_second" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                        ),
                        "y_radians_per_second" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                        ),
                        "z_radians_per_second" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                        ),
                    ),
                ),
            ),
        ),
        "interventions.v1" to CollectorEventContract(
            payloadSchemaVersion = 1,
            maximumEncodedEventBytes = 65_536,
            payloads = payloads(
                listOf("INTERVENTION_EXPIRED", "INTERVENTION_OPENED", "INTERVENTION_RESCHEDULED", "INTERVENTION_SCHEDULED", "NOTIFICATION_POSTED", "SURVEY_EXPIRED", "SURVEY_OPENED") to EventPayloadContract(
                    fields = mapOf(
                        "intervention_id" to EventFieldContract(
                            type = EventFieldType.STRING,
                            required = true,
                            maximumLength = 64,
                        ),
                        "occurrence_id" to EventFieldContract(
                            type = EventFieldType.STRING,
                            required = true,
                            maximumLength = 64,
                        ),
                        "scheduled_for_utc_millis" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                        "trigger_id" to EventFieldContract(
                            type = EventFieldType.STRING,
                            required = true,
                            maximumLength = 64,
                        ),
                    ),
                ),
                listOf("SURVEY_SUBMITTED") to EventPayloadContract(
                    fields = mapOf(
                        "answers_json" to EventFieldContract(
                            type = EventFieldType.JSON_STRING,
                            required = true,
                            maximumLength = 61440,
                        ),
                        "intervention_id" to EventFieldContract(
                            type = EventFieldType.STRING,
                            required = true,
                            maximumLength = 64,
                        ),
                        "occurrence_id" to EventFieldContract(
                            type = EventFieldType.STRING,
                            required = true,
                            maximumLength = 64,
                        ),
                        "opened_time" to EventFieldContract(
                            type = EventFieldType.JSON_STRING,
                            required = true,
                        ),
                        "scheduled_for_utc_millis" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                        "scheduled_time" to EventFieldContract(
                            type = EventFieldType.JSON_STRING,
                            required = true,
                        ),
                        "submitted_time" to EventFieldContract(
                            type = EventFieldType.JSON_STRING,
                            required = true,
                        ),
                        "survey_id" to EventFieldContract(
                            type = EventFieldType.STRING,
                            required = true,
                            maximumLength = 64,
                        ),
                        "trigger_id" to EventFieldContract(
                            type = EventFieldType.STRING,
                            required = true,
                            maximumLength = 64,
                        ),
                    ),
                ),
            ),
        ),
        "keyboard_touch.v1" to CollectorEventContract(
            payloadSchemaVersion = 1,
            maximumEncodedEventBytes = 4_096,
            payloads = payloads(
                listOf("KEYBOARD_TOUCH") to EventPayloadContract(
                    fields = mapOf(
                        "action" to EventFieldContract(
                            type = EventFieldType.ENUM,
                            required = true,
                            enumValues = setOf("CANCEL", "DOWN", "MOVE", "UP"),
                        ),
                        "down_uptime_millis" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                        "event_uptime_millis" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                        "geometry_version" to EventFieldContract(
                            type = EventFieldType.ENUM,
                            required = true,
                            enumValues = setOf("qwerty-v1"),
                        ),
                        "key_category" to EventFieldContract(
                            type = EventFieldType.ENUM,
                            required = true,
                            enumValues = setOf("BACKSPACE", "ENTER", "LETTER", "SPACE"),
                        ),
                        "orientation_radians" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                        ),
                        "pointer_id" to EventFieldContract(
                            type = EventFieldType.INT32,
                            required = true,
                            minimum = 0.0,
                        ),
                        "pressure" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                        ),
                        "relative_x" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                            minimum = 0.0,
                            maximum = 1.0,
                        ),
                        "relative_y" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                            minimum = 0.0,
                            maximum = 1.0,
                        ),
                        "size" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                        ),
                        "tool_type" to EventFieldContract(
                            type = EventFieldType.INT32,
                            required = true,
                        ),
                    ),
                ),
            ),
        ),
        "location.v1" to CollectorEventContract(
            payloadSchemaVersion = 1,
            maximumEncodedEventBytes = 4_096,
            payloads = payloads(
                listOf("LOCATION_FIX") to EventPayloadContract(
                    fields = mapOf(
                        "altitude_meters" to EventFieldContract(
                            type = EventFieldType.FLOAT64,
                            required = false,
                        ),
                        "bearing_accuracy_degrees" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = false,
                            minimum = 0.0,
                        ),
                        "bearing_degrees" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = false,
                            minimum = 0.0,
                            maximum = 360.0,
                        ),
                        "horizontal_accuracy_meters" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                            minimum = 0.0,
                        ),
                        "latitude_degrees" to EventFieldContract(
                            type = EventFieldType.FLOAT64,
                            required = true,
                            minimum = -90.0,
                            maximum = 90.0,
                        ),
                        "longitude_degrees" to EventFieldContract(
                            type = EventFieldType.FLOAT64,
                            required = true,
                            minimum = -180.0,
                            maximum = 180.0,
                        ),
                        "mock" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = true,
                        ),
                        "source_elapsed_realtime_nanos" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                        "source_time_utc_millis" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                        "speed_accuracy_meters_per_second" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = false,
                            minimum = 0.0,
                        ),
                        "speed_meters_per_second" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = false,
                            minimum = 0.0,
                        ),
                        "vertical_accuracy_meters" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = false,
                            minimum = 0.0,
                        ),
                    ),
                ),
            ),
        ),
        "network_state.v1" to CollectorEventContract(
            payloadSchemaVersion = 1,
            maximumEncodedEventBytes = 4_096,
            payloads = payloads(
                listOf("NETWORK_AVAILABLE", "NETWORK_LOST") to EventPayloadContract(
                    fields = mapOf(
                    ),
                ),
                listOf("NETWORK_CAPABILITIES") to EventPayloadContract(
                    fields = mapOf(
                        "downstream_kbps" to EventFieldContract(
                            type = EventFieldType.INT32,
                            required = false,
                            minimum = 0.0,
                        ),
                        "ethernet" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = true,
                        ),
                        "metered" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = true,
                        ),
                        "mobile" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = true,
                        ),
                        "roaming" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = true,
                        ),
                        "upstream_kbps" to EventFieldContract(
                            type = EventFieldType.INT32,
                            required = false,
                            minimum = 0.0,
                        ),
                        "validated" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = true,
                        ),
                        "vpn" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = true,
                        ),
                        "wifi" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = true,
                        ),
                    ),
                ),
                listOf("NETWORK_SNAPSHOT") to EventPayloadContract(
                    fields = mapOf(
                        "connected" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = true,
                        ),
                        "downstream_kbps" to EventFieldContract(
                            type = EventFieldType.INT32,
                            required = false,
                            minimum = 0.0,
                        ),
                        "ethernet" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = false,
                        ),
                        "metered" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = false,
                        ),
                        "mobile" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = false,
                        ),
                        "roaming" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = false,
                        ),
                        "upstream_kbps" to EventFieldContract(
                            type = EventFieldType.INT32,
                            required = false,
                            minimum = 0.0,
                        ),
                        "validated" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = false,
                        ),
                        "vpn" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = false,
                        ),
                        "wifi" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = false,
                        ),
                    ),
                ),
            ),
        ),
        "network_usage.v1" to CollectorEventContract(
            payloadSchemaVersion = 1,
            maximumEncodedEventBytes = 2_048,
            payloads = payloads(
                listOf("NETWORK_USAGE_AGGREGATE") to EventPayloadContract(
                    fields = mapOf(
                        "coverage_end_utc_millis" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                        "coverage_start_utc_millis" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                        "rx_bytes" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                        "rx_packets" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                        "transport" to EventFieldContract(
                            type = EventFieldType.ENUM,
                            required = true,
                            enumValues = setOf("MOBILE", "WIFI"),
                        ),
                        "tx_bytes" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                        "tx_packets" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                    ),
                ),
            ),
        ),
        "proximity.v1" to CollectorEventContract(
            payloadSchemaVersion = 1,
            maximumEncodedEventBytes = 1_024,
            payloads = payloads(
                listOf("PROXIMITY_SAMPLE") to EventPayloadContract(
                    fields = mapOf(
                        "distance_centimeters" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                            minimum = 0.0,
                        ),
                        "maximum_range_centimeters" to EventFieldContract(
                            type = EventFieldType.FLOAT32,
                            required = true,
                            minimum = 0.0,
                        ),
                        "near" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = true,
                        ),
                        "source_elapsed_realtime_nanos" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                    ),
                ),
            ),
        ),
        "temporal_context.v1" to CollectorEventContract(
            payloadSchemaVersion = 1,
            maximumEncodedEventBytes = 1_024,
            payloads = payloads(
                listOf("TEMPORAL_CONTEXT") to EventPayloadContract(
                    fields = mapOf(
                        "change_reason" to EventFieldContract(
                            type = EventFieldType.ENUM,
                            required = true,
                            enumValues = setOf("RECONCILED", "STUDY_STARTED", "TIMEZONE_CHANGED", "TIME_SET", "UTC_OFFSET_CHANGED"),
                        ),
                        "daylight_saving_time" to EventFieldContract(
                            type = EventFieldType.BOOLEAN,
                            required = true,
                        ),
                        "timezone_id" to EventFieldContract(
                            type = EventFieldType.STRING,
                            required = true,
                            maximumLength = 128,
                        ),
                        "utc_offset_seconds" to EventFieldContract(
                            type = EventFieldType.INT32,
                            required = true,
                            minimum = -64800.0,
                            maximum = 64800.0,
                        ),
                    ),
                ),
            ),
        ),
        "usage_events.v1" to CollectorEventContract(
            payloadSchemaVersion = 1,
            maximumEncodedEventBytes = 4_096,
            payloads = payloads(
                listOf("ACTIVITY_PAUSED", "ACTIVITY_RESUMED", "ACTIVITY_STOPPED", "DEVICE_SHUTDOWN", "DEVICE_STARTUP", "KEYGUARD_HIDDEN", "KEYGUARD_SHOWN", "SCREEN_INTERACTIVE", "SCREEN_NON_INTERACTIVE") to EventPayloadContract(
                    fields = mapOf(
                        "package_name" to EventFieldContract(
                            type = EventFieldType.STRING,
                            required = false,
                            maximumLength = 255,
                        ),
                        "source_time_utc_millis" to EventFieldContract(
                            type = EventFieldType.DECIMAL_STRING,
                            required = true,
                        ),
                    ),
                ),
            ),
        ),
    )

    operator fun get(collectorId: String): CollectorEventContract? = contracts[collectorId]

    private fun payloads(
        vararg groups: Pair<List<String>, EventPayloadContract>,
    ): Map<String, EventPayloadContract> = buildMap {
        groups.forEach { (types, contract) ->
            types.forEach { type -> check(put(type, contract) == null) { "Duplicate payload type" } }
        }
    }
}
